version: "3.8"
services:
  web:
    build: ./
    depends_on:
      - api
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
       - network-backend
  api:
    build: ./backend
    # depends_on:
    #   - mongo
    ports:
      - "5000:5000"
    networks:
      - network-backend
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  network-backend:
