version: "3.8"
services:
  web:
    build: ./
    depends_on:
      - myapi
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
       - network-backend
  myapi:
    build: ./backend
    # depends_on:
    #   - mongo
    ports:
      - "5000:5000"
    networks:
      - network-backend

networks:
  network-backend:
